name: Jekyll Themes
url: http://matt.harzewski.com
description: Insert tagline here

permalink: /themes/:title/

gems: [jekyll-paginate]

highlighter: pygments
paginate: 20

markdown: rdiscount
rdiscount:
    extensions: ['smart']

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile', 'vendor']

theme: jekyll-theme-cayman